version: '3.9'

services:
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    depends_on:
#      - zookeeper
#    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=kafka
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_MAX_REQUEST_SIZE=10485760
  predicttheforex_extractor:
    image: predicttheforex_extractor
    build:
      context: .
      dockerfile: Dockerfile
    command:
      # windows environments:
      - uvicorn core.main:app --host 0.0.0.0 --port 8000
      # Unix environments
      # bash -c "sleep 10 && uvicorn core.main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    #depends_on:
    #  - kafka
    #environment:
    #  - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

